// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhfUtw1uBgiWDTonUNHoqy5tJ4PfJ5SKI',
    appId: '1:952711967353:web:6aeaaeac2113ecd9dfdaa8',
    messagingSenderId: '952711967353',
    projectId: 'carehub-ad1bc',
    authDomain: 'carehub-ad1bc.firebaseapp.com',
    databaseURL: 'https://carehub-ad1bc-default-rtdb.firebaseio.com',
    storageBucket: 'carehub-ad1bc.firebasestorage.app',
    measurementId: 'G-W55WN0Y41X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa548ryd0ioyB0uyu6dOlpjzRZ0VcVL44',
    appId: '1:952711967353:android:d0e977a983c6c4fcdfdaa8',
    messagingSenderId: '952711967353',
    projectId: 'carehub-ad1bc',
    databaseURL: 'https://carehub-ad1bc-default-rtdb.firebaseio.com',
    storageBucket: 'carehub-ad1bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoi9jOSWss93BERqaycM9C9j8cq5G09NI',
    appId: '1:952711967353:ios:deb8c6c9f37fcfe3dfdaa8',
    messagingSenderId: '952711967353',
    projectId: 'carehub-ad1bc',
    databaseURL: 'https://carehub-ad1bc-default-rtdb.firebaseio.com',
    storageBucket: 'carehub-ad1bc.firebasestorage.app',
    androidClientId: '952711967353-h6carinbc2g0kcgfugpiett8e96831c6.apps.googleusercontent.com',
    iosClientId: '952711967353-vulf7eo3ofm7q2b0nn42jskmjgh33t57.apps.googleusercontent.com',
    iosBundleId: 'tiendev.socialmate.vn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoi9jOSWss93BERqaycM9C9j8cq5G09NI',
    appId: '1:952711967353:ios:508cadab34859cb5dfdaa8',
    messagingSenderId: '952711967353',
    projectId: 'carehub-ad1bc',
    databaseURL: 'https://carehub-ad1bc-default-rtdb.firebaseio.com',
    storageBucket: 'carehub-ad1bc.firebasestorage.app',
    androidClientId: '952711967353-h6carinbc2g0kcgfugpiett8e96831c6.apps.googleusercontent.com',
    iosClientId: '952711967353-eq410otektf63rfuteclm7t2r103r94c.apps.googleusercontent.com',
    iosBundleId: 'com.socialmate.vn.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhfUtw1uBgiWDTonUNHoqy5tJ4PfJ5SKI',
    appId: '1:952711967353:web:6aeaaeac2113ecd9dfdaa8',
    messagingSenderId: '952711967353',
    projectId: 'carehub-ad1bc',
    authDomain: 'carehub-ad1bc.firebaseapp.com',
    databaseURL: 'https://carehub-ad1bc-default-rtdb.firebaseio.com',
    storageBucket: 'carehub-ad1bc.firebasestorage.app',
    measurementId: 'G-W55WN0Y41X',
  );

}